apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaceplanets
  labels:
    app: spaceplanets
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spaceplanets
  template:
    metadata:
      labels:
        app: spaceplanets
    spec:
      containers:
      - name: spaceplanets
        image: registryhostname:5000/imagename:tag
        ports:
        - containerPort: 80
        env:
        - name: SPACEPLANETS_MONGODB_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: spaceplanets-mongodb-connectionstring
              key: string
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: secrets
          mountPath: settings
          readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: secrets
        secret:
          secretName: spaceplanets-appsettings